### Registration
POST localhost:8080/registration/api/register
Accept-Language: EN
Content-Type: application/json

{
  "name": "Sanjar",
  "email": "sanjarbeksultanov2025@gmail.com",
  "password": "1",
  "birthDate": "2003-07-27"
}
