### Get by phone
GET http://localhost:8080/sms-history/api/getByPhone?phone=+998337271031
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTE2OTc2OTEsImVtYWlsIjoic2FuamFyYmVrc3VsdGFub3YyMDIzQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzExNzg0MDkxLCJpc3MiOiJDaG9wYXJQcm8ifQ.MbfR8qPd3eMCty3vMOUF71SdhaYmIS3ab3_l7Gpwvj9jq8me11FUrU3TeHrUCf2k8G1h0GedoqHOjG33CPNT_A

### Get by date
GET http://localhost:8080/sms-history/api/getByDate?date=2024-03-29
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTE2OTc2OTEsImVtYWlsIjoic2FuamFyYmVrc3VsdGFub3YyMDIzQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzExNzg0MDkxLCJpc3MiOiJDaG9wYXJQcm8ifQ.MbfR8qPd3eMCty3vMOUF71SdhaYmIS3ab3_l7Gpwvj9jq8me11FUrU3TeHrUCf2k8G1h0GedoqHOjG33CPNT_A

### Get by pagination
GET http://localhost:8080/sms-history/api/getByPagination?page=1&size=2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTE2OTc2OTEsImVtYWlsIjoic2FuamFyYmVrc3VsdGFub3YyMDIzQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzExNzg0MDkxLCJpc3MiOiJDaG9wYXJQcm8ifQ.MbfR8qPd3eMCty3vMOUF71SdhaYmIS3ab3_l7Gpwvj9jq8me11FUrU3TeHrUCf2k8G1h0GedoqHOjG33CPNT_A
